using System;
using System.Linq;
using UnityEngine;
using Vaga;
using Vaga.Classes;
using Vaga.Mods;
using Vaga.Mods.Exploits;
using static Vaga.Menu.Main;
using static Vaga.Settings;

namespace Vaga.Menu
{
    public class Buttons
    {
        public static ButtonInfo GetCategory(string name)
        {
            if (buttons == null) return null;
            return buttons.SelectMany(b => b).FirstOrDefault(c => c.buttonText == name);
        }

        public static bool ghostview = true;

        public static void ToggleRightHand()
        {
            rightHanded = !rightHanded;
        }

        public static void ToggleNotifications()
        {
            disableNotifications = !disableNotifications;
            MenuStubs.Notifs();
        }


        public static ButtonInfo[][] buttons = new ButtonInfo[][]
        {
                        // 0 Home — Fade.wtf style category list
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "Visuals", method = () => currentCategory = 6, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "GameMode", method = () => currentCategory = 5, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Exploits", method = () => currentCategory = 9, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Serversided", method = () => currentCategory = 8, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Movement", method = () => currentCategory = 3, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Players", method = () => currentCategory = 4, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Global", method = () => currentCategory = 7, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "AntiBan", method = () => currentCategory = 10, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Master", method = () => currentCategory = 11, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Infection", method = () => currentCategory = 12, isTogglable = false, toolTip = "View Modules" },
                new ButtonInfo { buttonText = "Settings", method = () => currentCategory = 1, isTogglable = false, toolTip = "View Modules" },
},
            // 1 Settings
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Desktop GUI", enableMethod = () => { DesktopGuiHost.Ensure(); DesktopGui.Visible = true; }, disableMethod = () => DesktopGui.Visible = false, toolTip = "Optional PC overlay (off by default)" },
                new ButtonInfo { buttonText = "GUI Key Cycle", method = () => DesktopGui.CycleToggleKey(), isTogglable = false, toolTip = "Cycle GUI toggle key" },
                new ButtonInfo { buttonText = "GUI Key Rebind", method = () => DesktopGui.StartRebind(), isTogglable = false, toolTip = "Next key pressed becomes bind" },
                new ButtonInfo { buttonText = "Reload UI Bundle", method = () => { UiTheme.Unload(); UiTheme.Ensure(); }, isTogglable = false, toolTip = "Reload morphine_ui AssetBundle" },
                                                new ButtonInfo { buttonText = "Intensity Low", method = () => ExploitSettings.SetLow(), isTogglable = false, toolTip = "All exploits Low" },
                new ButtonInfo { buttonText = "Intensity Mid", method = () => ExploitSettings.SetMid(), isTogglable = false, toolTip = "All exploits Medium" },
                new ButtonInfo { buttonText = "Intensity High", method = () => ExploitSettings.SetHigh(), isTogglable = false, toolTip = "All exploits High" },
                new ButtonInfo { buttonText = "Intensity Extreme", method = () => ExploitSettings.SetExtreme(), isTogglable = false, toolTip = "All exploits Extreme" },
                new ButtonInfo { buttonText = "Barrel Low", method = () => ExploitSettings.SetBarrelLow(), isTogglable = false, toolTip = "Barrel fling Low" },
                new ButtonInfo { buttonText = "Barrel Mid", method = () => ExploitSettings.SetBarrelMid(), isTogglable = false, toolTip = "Barrel fling Medium" },
                new ButtonInfo { buttonText = "Barrel High", method = () => ExploitSettings.SetBarrelHigh(), isTogglable = false, toolTip = "Barrel fling High" },
                new ButtonInfo { buttonText = "Barrel Extreme", method = () => ExploitSettings.SetBarrelExtreme(), isTogglable = false, toolTip = "Barrel fling Extreme" },
                new ButtonInfo { buttonText = "Lag Intensity", method = () => ExploitSettings.CycleLag(), isTogglable = false, toolTip = "Cycle lag strength Low->Extreme" },
                new ButtonInfo { buttonText = "Crash Intensity", method = () => ExploitSettings.CycleCrash(), isTogglable = false, toolTip = "Cycle crash burst strength" },
                new ButtonInfo { buttonText = "Variance / Jitter", method = () => ExploitSettings.CycleVariance(), isTogglable = false, toolTip = "Timing variance for stealth" },
                new ButtonInfo { buttonText = "Payload Size", method = () => ExploitSettings.CyclePayload(), isTogglable = false, toolTip = "Packet payload size" },
                new ButtonInfo { buttonText = "Ownership Flips", method = () => ExploitSettings.CycleOwnership(), isTogglable = false, toolTip = "Ownership thrash amount" },
                new ButtonInfo { buttonText = "Preset Stealth", method = () => ExploitSettings.PresetStealth(), isTogglable = false, toolTip = "Low lag, high jitter" },
                new ButtonInfo { buttonText = "Preset Balanced", method = () => ExploitSettings.PresetBalanced(), isTogglable = false, toolTip = "Default medium" },
                new ButtonInfo { buttonText = "Preset Aggressive", method = () => ExploitSettings.PresetAggressive(), isTogglable = false, toolTip = "Max pressure" },
                new ButtonInfo { buttonText = "Exploit Status", method = () => ExploitSettings.Status(), isTogglable = false, toolTip = "Log current levels" },
                new ButtonInfo { buttonText = "Memory Monitor", enableMethod = () => MemoryMonitor.Enabled = true, disableMethod = () => MemoryMonitor.Enabled = false, method = () => MemoryMonitor.Update(), enabled = true, toolTip = "Track heap/GC spikes" },
                new ButtonInfo { buttonText = "Mem Overlay", enableMethod = () => { MemoryMonitor.Overlay = true; MemoryMonitorHost.Ensure(); }, disableMethod = () => MemoryMonitor.Overlay = false, toolTip = "On-screen mem stats" },
                new ButtonInfo { buttonText = "Mem Dump", method = () => MemoryMonitor.Dump(), isTogglable = false, toolTip = "Log full mem dump" },
                new ButtonInfo { buttonText = "Force GC", method = () => MemoryMonitor.ForceGc(), isTogglable = false, toolTip = "Force garbage collection" },

                new ButtonInfo { buttonText = "Theme", method = () => MenuStubs.ThemeCycle(), isTogglable = false, toolTip = "Theme" },
                new ButtonInfo { buttonText = "Menu Button", method = () => MenuStubs.MenuButtonCycle(), isTogglable = false, toolTip = "Menu Button" },
                new ButtonInfo { buttonText = "Open Animation", enableMethod = () => MenuStubs.OpenAnim = true, disableMethod = () => MenuStubs.OpenAnim = false, method = () => MenuStubs.TickMovement(), toolTip = "Open Animation" },
                new ButtonInfo { buttonText = "Button Animation", enableMethod = () => MenuStubs.ButtonAnim = true, disableMethod = () => MenuStubs.ButtonAnim = false, method = () => MenuStubs.TickMovement(), toolTip = "Button Animation" },
                new ButtonInfo { buttonText = "Animation Speed", method = () => MenuStubs.AnimSpeedCycle(), isTogglable = false, toolTip = "Animation Speed" },
                new ButtonInfo { buttonText = "Smooth Menu", enableMethod = () => MenuStubs.SmoothMenu = true, disableMethod = () => MenuStubs.SmoothMenu = false, method = () => MenuStubs.TickMovement(), toolTip = "Smooth Menu" },
                new ButtonInfo { buttonText = "Gun Style", method = () => MenuStubs.GunStyleCycle(), isTogglable = false, toolTip = "Gun Style" },
                new ButtonInfo { buttonText = "Gun Color", method = () => MenuStubs.GunColorCycle(), isTogglable = false, toolTip = "Gun Color" },
                new ButtonInfo { buttonText = "Gun Width", method = () => MenuStubs.GunWidthCycle(), isTogglable = false, toolTip = "Gun Width" },
                new ButtonInfo { buttonText = "Gun Speed", method = () => MenuStubs.GunSpeedCycle(), isTogglable = false, toolTip = "Gun Speed" },
                new ButtonInfo { buttonText = "Gun Size", method = () => MenuStubs.GunSizeCycle(), isTogglable = false, toolTip = "Gun Size" },
                new ButtonInfo { buttonText = "Gun Pointer", enableMethod = () => MenuStubs.GunPointer = true, disableMethod = () => MenuStubs.GunPointer = false, method = () => MenuStubs.TickMovement(), toolTip = "Gun Pointer" },
                new ButtonInfo { buttonText = "Gun Fade", enableMethod = () => MenuStubs.GunFade = true, disableMethod = () => MenuStubs.GunFade = false, method = () => MenuStubs.TickMovement(), toolTip = "Gun Fade" },
                new ButtonInfo { buttonText = "Gun Smooth", enableMethod = () => MenuStubs.GunSmooth = true, disableMethod = () => MenuStubs.GunSmooth = false, method = () => MenuStubs.TickMovement(), toolTip = "Gun Smooth" },
                new ButtonInfo { buttonText = "Gun Haptics", enableMethod = () => MenuStubs.GunHaptics = true, disableMethod = () => MenuStubs.GunHaptics = false, method = () => MenuStubs.TickMovement(), toolTip = "Gun Haptics" },
                new ButtonInfo { buttonText = "Gun Shoot Sound", method = () => MenuStubs.GunShootCycle(), isTogglable = false, toolTip = "Gun Shoot Sound" },
                new ButtonInfo { buttonText = "Gun Trigger Sound", method = () => MenuStubs.GunTrigCycle(), isTogglable = false, toolTip = "Gun Trigger Sound" },
                new ButtonInfo { buttonText = "Gun Effects", enableMethod = () => MenuStubs.GunEffects = true, disableMethod = () => MenuStubs.GunEffects = false, method = () => MenuStubs.TickMovement(), toolTip = "Gun Effects" },
                new ButtonInfo { buttonText = "Notifications", method = () => ToggleNotifications(), isTogglable = false, toolTip = "Notifications" },
                new ButtonInfo { buttonText = "Test Notification", method = () => MenuStubs.TestNotification(), isTogglable = false, toolTip = "Test Notification" },
                new ButtonInfo { buttonText = "Save Config", method = () => MenuStubs.SaveConfig(), isTogglable = false, toolTip = "Save Config" },
                new ButtonInfo { buttonText = "Load Config", method = () => MenuStubs.LoadConfig(), isTogglable = false, toolTip = "Load Config" },
                new ButtonInfo { buttonText = "Auto Load Config", enableMethod = () => MenuStubs.AutoLoadConfig = true, disableMethod = () => MenuStubs.AutoLoadConfig = false, method = () => MenuStubs.TickMovement(), toolTip = "Auto Load Config" },
                new ButtonInfo { buttonText = "Right Hand", method = () => ToggleRightHand(), isTogglable = false, toolTip = "Right Hand" },
            },
            // 2 SoundBoard
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Refresh", method = () => MenuStubs.SoundBoardRefresh(), isTogglable = false, toolTip = "Refresh" },
                new ButtonInfo { buttonText = "Loop Sounds", method = () => MenuStubs.LoopSounds(), isTogglable = false, toolTip = "Loop Sounds" },
            },
            // 3 Movement
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "WASD", method = () => Movement.WASDFly(), toolTip = "WASD Fly" },
                new ButtonInfo { buttonText = "Platforms", method = () => Movement.Platforms(), toolTip = "Platforms" },
                new ButtonInfo { buttonText = "Fly", method = () => Movement.Fly(), toolTip = "Fly A" },
                new ButtonInfo { buttonText = "Vaga Fly", method = () => Movement.VagaFly(), toolTip = "Grip fly" },
                new ButtonInfo { buttonText = "Platform Gun", enableMethod = () => MenuStubs.PlatformGun = true, disableMethod = () => MenuStubs.PlatformGun = false, method = () => MenuStubs.TickMovement(), toolTip = "Platform Gun" },
                new ButtonInfo { buttonText = "Platform Spammer", enableMethod = () => MenuStubs.PlatformSpammer = true, disableMethod = () => MenuStubs.PlatformSpammer = false, method = () => MenuStubs.TickMovement(), toolTip = "Platform Spammer" },
                new ButtonInfo { buttonText = "Trigger Fly", enableMethod = () => MenuStubs.TriggerFly = true, disableMethod = () => MenuStubs.TriggerFly = false, method = () => MenuStubs.TickMovement(), toolTip = "Trigger Fly" },
                new ButtonInfo { buttonText = "No Clip Fly", enableMethod = () => MenuStubs.NoClipFly = true, disableMethod = () => MenuStubs.NoClipFly = false, method = () => MenuStubs.TickMovement(), toolTip = "No Clip Fly" },
                new ButtonInfo { buttonText = "Hand Fly", enableMethod = () => MenuStubs.HandFly = true, disableMethod = () => MenuStubs.HandFly = false, method = () => MenuStubs.TickMovement(), toolTip = "Hand Fly" },
                new ButtonInfo { buttonText = "Slingshot Fly", enableMethod = () => MenuStubs.SlingshotFly = true, disableMethod = () => MenuStubs.SlingshotFly = false, method = () => MenuStubs.TickMovement(), toolTip = "Slingshot Fly" },
                new ButtonInfo { buttonText = "Joystick Fly", enableMethod = () => MenuStubs.JoystickFly = true, disableMethod = () => MenuStubs.JoystickFly = false, method = () => MenuStubs.TickMovement(), toolTip = "Joystick Fly" },
                new ButtonInfo { buttonText = "Zero Gravity Fly", enableMethod = () => MenuStubs.ZeroGFly = true, disableMethod = () => MenuStubs.ZeroGFly = false, method = () => MenuStubs.TickMovement(), toolTip = "Zero Gravity Fly" },
                new ButtonInfo { buttonText = "Up And Down", enableMethod = () => MenuStubs.UpDown = true, disableMethod = () => MenuStubs.UpDown = false, method = () => MenuStubs.TickMovement(), toolTip = "Up And Down" },
                new ButtonInfo { buttonText = "Left And Right", enableMethod = () => MenuStubs.LeftRight = true, disableMethod = () => MenuStubs.LeftRight = false, method = () => MenuStubs.TickMovement(), toolTip = "Left And Right" },
                new ButtonInfo { buttonText = "C4", enableMethod = () => MenuStubs.C4 = true, disableMethod = () => MenuStubs.C4 = false, method = () => MenuStubs.TickMovement(), toolTip = "C4" },
                new ButtonInfo { buttonText = "No Clip", enableMethod = () => MenuStubs.NoClip = true, disableMethod = () => MenuStubs.NoClip = false, method = () => MenuStubs.TickMovement(), toolTip = "No Clip" },
                new ButtonInfo { buttonText = "Steam Long Arms", enableMethod = () => MenuStubs.SteamLongArms = true, disableMethod = () => MenuStubs.SteamLongArms = false, method = () => MenuStubs.TickMovement(), toolTip = "Steam Long Arms" },
                new ButtonInfo { buttonText = "Really Long Arms", enableMethod = () => MenuStubs.ReallyLongArms = true, disableMethod = () => MenuStubs.ReallyLongArms = false, method = () => MenuStubs.TickMovement(), toolTip = "Really Long Arms" },
                new ButtonInfo { buttonText = "Legit Long Arms", enableMethod = () => MenuStubs.LegitLongArms = true, disableMethod = () => MenuStubs.LegitLongArms = false, method = () => MenuStubs.TickMovement(), toolTip = "Legit Long Arms" },
                new ButtonInfo { buttonText = "Normal Arms", enableMethod = () => MenuStubs.NormalArms = true, disableMethod = () => MenuStubs.NormalArms = false, method = () => MenuStubs.TickMovement(), toolTip = "Normal Arms" },
                new ButtonInfo { buttonText = "Speed Boost", enableMethod = () => MenuStubs.SpeedBoost = true, disableMethod = () => MenuStubs.SpeedBoost = false, method = () => MenuStubs.TickMovement(), toolTip = "Speed Boost" },
                new ButtonInfo { buttonText = "Integrated Speedboost", enableMethod = () => MenuStubs.IntegratedSpeed = true, disableMethod = () => MenuStubs.IntegratedSpeed = false, method = () => MenuStubs.TickMovement(), toolTip = "Integrated Speedboost" },
                new ButtonInfo { buttonText = "Grip Speedboost", enableMethod = () => MenuStubs.GripSpeed = true, disableMethod = () => MenuStubs.GripSpeed = false, method = () => MenuStubs.TickMovement(), toolTip = "Grip Speedboost" },
                new ButtonInfo { buttonText = "Pull Mod", enableMethod = () => MenuStubs.PullMod = true, disableMethod = () => MenuStubs.PullMod = false, method = () => MenuStubs.TickMovement(), toolTip = "Pull Mod" },
                new ButtonInfo { buttonText = "Slide Control", enableMethod = () => MenuStubs.SlideControl = true, disableMethod = () => MenuStubs.SlideControl = false, method = () => MenuStubs.TickMovement(), toolTip = "Slide Control" },
                new ButtonInfo { buttonText = "Force Tag Freeze", enableMethod = () => MenuStubs.ForceTagFreeze = true, disableMethod = () => MenuStubs.ForceTagFreeze = false, method = () => MenuStubs.TickMovement(), toolTip = "Force Tag Freeze" },
                new ButtonInfo { buttonText = "No Tag Freeze", enableMethod = () => MenuStubs.NoTagFreeze = true, disableMethod = () => MenuStubs.NoTagFreeze = false, method = () => MenuStubs.TickMovement(), toolTip = "No Tag Freeze" },
                new ButtonInfo { buttonText = "Uncap Speed", enableMethod = () => MenuStubs.UncapSpeed = true, disableMethod = () => MenuStubs.UncapSpeed = false, method = () => MenuStubs.TickMovement(), toolTip = "Uncap Speed" },
                new ButtonInfo { buttonText = "Super Jump", enableMethod = () => MenuStubs.SuperJump = true, disableMethod = () => MenuStubs.SuperJump = false, method = () => MenuStubs.TickMovement(), toolTip = "Super Jump" },
                new ButtonInfo { buttonText = "Wall Walk", enableMethod = () => MenuStubs.WallWalk = true, disableMethod = () => MenuStubs.WallWalk = false, method = () => MenuStubs.TickMovement(), toolTip = "Wall Walk" },
                new ButtonInfo { buttonText = "Iron Monkey", enableMethod = () => MenuStubs.IronMonkey = true, disableMethod = () => MenuStubs.IronMonkey = false, method = () => MenuStubs.TickMovement(), toolTip = "Iron Monkey" },
            },
            // 4 VRRig
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Ghost Monkey", enableMethod = () => GhostVariants.LocalGhostMonkey = true, disableMethod = () => GhostVariants.LocalGhostMonkey = false, method = () => GhostVariants.Update(), toolTip = "Ghost Monkey" },
                new ButtonInfo { buttonText = "Invis Monkey", enableMethod = () => GhostVariants.LocalInvisMonkey = true, disableMethod = () => GhostVariants.LocalInvisMonkey = false, method = () => GhostVariants.Update(), toolTip = "Invis Monkey" },
                new ButtonInfo { buttonText = "Grab Rig", enableMethod = () => MenuStubs.GrabRig = true, disableMethod = () => MenuStubs.GrabRig = false, method = () => MenuStubs.TickMovement(), toolTip = "Grab Rig" },
                new ButtonInfo { buttonText = "Helicopter Rig", enableMethod = () => MenuStubs.HelicopterRig = true, disableMethod = () => MenuStubs.HelicopterRig = false, method = () => MenuStubs.TickMovement(), toolTip = "Helicopter Rig" },
                new ButtonInfo { buttonText = "Rig Macro", enableMethod = () => MenuStubs.RigMacro = true, disableMethod = () => MenuStubs.RigMacro = false, method = () => MenuStubs.TickMovement(), toolTip = "Rig Macro" },
                new ButtonInfo { buttonText = "RGB Monkey", enableMethod = () => MenuStubs.RGBMonkey = true, disableMethod = () => MenuStubs.RGBMonkey = false, method = () => MenuStubs.TickMovement(), toolTip = "RGB Monkey" },
                new ButtonInfo { buttonText = "Strobe Monkey", enableMethod = () => MenuStubs.StrobeMonkey = true, disableMethod = () => MenuStubs.StrobeMonkey = false, method = () => MenuStubs.TickMovement(), toolTip = "Strobe Monkey" },
                new ButtonInfo { buttonText = "Flash Color", enableMethod = () => MenuStubs.FlashColor = true, disableMethod = () => MenuStubs.FlashColor = false, method = () => MenuStubs.TickMovement(), toolTip = "Flash Color" },
                new ButtonInfo { buttonText = "Strobe Color", enableMethod = () => MenuStubs.StrobeColor = true, disableMethod = () => MenuStubs.StrobeColor = false, method = () => MenuStubs.TickMovement(), toolTip = "Strobe Color" },
                new ButtonInfo { buttonText = "Rainbow Color", enableMethod = () => MenuStubs.RainbowColor = true, disableMethod = () => MenuStubs.RainbowColor = false, method = () => MenuStubs.TickMovement(), toolTip = "Rainbow Color" },
                new ButtonInfo { buttonText = "Hard Rainbow Color", enableMethod = () => MenuStubs.HardRainbow = true, disableMethod = () => MenuStubs.HardRainbow = false, method = () => MenuStubs.TickMovement(), toolTip = "Hard Rainbow Color" },
                new ButtonInfo { buttonText = "Sex Gun", enableMethod = () => MenuStubs.SexGun = true, disableMethod = () => MenuStubs.SexGun = false, method = () => MenuStubs.TickMovement(), toolTip = "Sex Gun" },
                new ButtonInfo { buttonText = "Spectate Gun", enableMethod = () => MenuStubs.SpectateGun = true, disableMethod = () => MenuStubs.SpectateGun = false, method = () => MenuStubs.TickMovement(), toolTip = "Spectate Gun" },
                new ButtonInfo { buttonText = "Scare Gun", enableMethod = () => MenuStubs.ScareGun = true, disableMethod = () => MenuStubs.ScareGun = false, method = () => MenuStubs.TickMovement(), toolTip = "Scare Gun" },
                new ButtonInfo { buttonText = "Copy Movement Gun", enableMethod = () => MenuStubs.CopyMoveGun = true, disableMethod = () => MenuStubs.CopyMoveGun = false, method = () => MenuStubs.TickMovement(), toolTip = "Copy Movement Gun" },
                new ButtonInfo { buttonText = "Copy Player Gun", enableMethod = () => MenuStubs.CopyPlayerGun = true, disableMethod = () => MenuStubs.CopyPlayerGun = false, method = () => MenuStubs.TickMovement(), toolTip = "Copy Player Gun" },
                new ButtonInfo { buttonText = "Copy Identity Gun", enableMethod = () => MenuStubs.CopyIdGun = true, disableMethod = () => MenuStubs.CopyIdGun = false, method = () => MenuStubs.TickMovement(), toolTip = "Copy Identity Gun" },
                new ButtonInfo { buttonText = "Punch Mod", enableMethod = () => MenuStubs.PunchMod = true, disableMethod = () => MenuStubs.PunchMod = false, method = () => MenuStubs.TickMovement(), toolTip = "Punch Mod" },
                new ButtonInfo { buttonText = "Spaz Head", enableMethod = () => MenuStubs.SpazHead = true, disableMethod = () => MenuStubs.SpazHead = false, method = () => MenuStubs.TickMovement(), toolTip = "Spaz Head" },
                new ButtonInfo { buttonText = "Spin Head X", enableMethod = () => MenuStubs.SpinHeadX = true, disableMethod = () => MenuStubs.SpinHeadX = false, method = () => MenuStubs.TickMovement(), toolTip = "Spin Head X" },
                new ButtonInfo { buttonText = "Spin Head Y", enableMethod = () => MenuStubs.SpinHeadY = true, disableMethod = () => MenuStubs.SpinHeadY = false, method = () => MenuStubs.TickMovement(), toolTip = "Spin Head Y" },
                new ButtonInfo { buttonText = "Spin Head Z", enableMethod = () => MenuStubs.SpinHeadZ = true, disableMethod = () => MenuStubs.SpinHeadZ = false, method = () => MenuStubs.TickMovement(), toolTip = "Spin Head Z" },
                new ButtonInfo { buttonText = "Cosmetic Bypass", enableMethod = () => MenuStubs.CosmeticBypass = true, disableMethod = () => MenuStubs.CosmeticBypass = false, method = () => MenuStubs.TickMovement(), toolTip = "Cosmetic Bypass" },
                new ButtonInfo { buttonText = "Master Lock", enableMethod = () => AntiBan.MasterClientLock = true, disableMethod = () => AntiBan.MasterClientLock = false, method = () => AntiBan.Update(), toolTip = "Master lock" },
                new ButtonInfo { buttonText = "Sticky Lock", enableMethod = () => GunLib.StickyLock = true, disableMethod = () => GunLib.StickyLock = false, enabled = true, toolTip = "Gun sticky hitbox lock" },
            },
            // 5 GameMode
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Tag All", method = () => TagGuardian.TagAll(), isTogglable = false, toolTip = "Tag All" },
                new ButtonInfo { buttonText = "Tag Gun", enableMethod = () => TagGuardian.TagGunEnabled = true, disableMethod = () => TagGuardian.TagGunEnabled = false, method = () => TagGuardian.Update(), toolTip = "Tag Gun" },
                new ButtonInfo { buttonText = "Tag Self", method = () => TagGuardian.TagSelf(), isTogglable = false, toolTip = "Tag Self" },
                new ButtonInfo { buttonText = "Tag Bot Loop", enableMethod = () => TagBotLoop.Enabled = true, disableMethod = () => TagBotLoop.Enabled = false, method = () => TagBotLoop.Update(), toolTip = "Tag others then self loop" },
                new ButtonInfo { buttonText = "Kick To Infection", method = () => { KickToGamemode.SetMode("infection"); KickToGamemode.KickAll(); }, isTogglable = false, toolTip = "Kick all to infection" },
                new ButtonInfo { buttonText = "Kick To Casual", method = () => { KickToGamemode.SetMode("casual"); KickToGamemode.KickAll(); }, isTogglable = false, toolTip = "Kick all to casual" },
                new ButtonInfo { buttonText = "Kick To Hunt", method = () => { KickToGamemode.SetMode("hunt"); KickToGamemode.KickAll(); }, isTogglable = false, toolTip = "Kick all to hunt" },
                new ButtonInfo { buttonText = "Kick To Paintbrawl", method = () => { KickToGamemode.SetMode("paintbrawl"); KickToGamemode.KickAll(); }, isTogglable = false, toolTip = "Kick all to paintbrawl" },
                new ButtonInfo { buttonText = "Kick To Freeze Tag", method = () => { KickToGamemode.SetMode("freezetag"); KickToGamemode.KickAll(); }, isTogglable = false, toolTip = "Kick all to freeze tag" },
                new ButtonInfo { buttonText = "Kick GM Gun", enableMethod = () => KickToGamemode.GunEnabled = true, disableMethod = () => KickToGamemode.GunEnabled = false, method = () => KickToGamemode.Update(), toolTip = "Kick target to selected GM" },

                new ButtonInfo { buttonText = "Guardian Grab All", method = () => TagGuardian.GuardianGrabAll(), isTogglable = false, toolTip = "Guardian Grab All" },
                new ButtonInfo { buttonText = "Guardian Grab Gun", enableMethod = () => TagGuardian.GuardianGrabGunEnabled = true, disableMethod = () => TagGuardian.GuardianGrabGunEnabled = false, method = () => TagGuardian.Update(), toolTip = "Guardian Grab Gun" },
                new ButtonInfo { buttonText = "Guardian Fling All", method = () => TagGuardian.GuardianFlingAll(), isTogglable = false, toolTip = "Guardian Fling All" },
                new ButtonInfo { buttonText = "Guardian Fling Gun", enableMethod = () => TagGuardian.GuardianFlingGunEnabled = true, disableMethod = () => TagGuardian.GuardianFlingGunEnabled = false, method = () => TagGuardian.Update(), toolTip = "Guardian Fling Gun" },
                new ButtonInfo { buttonText = "Guardian Fly All", method = () => TagGuardian.GuardianFlyAll(), isTogglable = false, toolTip = "Guardian Fly All" },
                new ButtonInfo { buttonText = "Guardian Fly Gun", enableMethod = () => TagGuardian.GuardianFlyGunEnabled = true, disableMethod = () => TagGuardian.GuardianFlyGunEnabled = false, method = () => TagGuardian.Update(), toolTip = "Guardian Fly Gun" },
            },
            // 6 Visuals
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Chams", enableMethod = () => VisualESP.Chams = true, disableMethod = () => VisualESP.Chams = false, method = () => VisualESP.Update(), toolTip = "Chams" },
                new ButtonInfo { buttonText = "Chams Shader", enableMethod = () => VisualESP.Chams = true, disableMethod = () => VisualESP.Chams = false, method = () => VisualESP.Update(), toolTip = "Chams" },
                new ButtonInfo { buttonText = "Chams Color", enableMethod = () => VisualESP.Chams = true, disableMethod = () => VisualESP.Chams = false, method = () => VisualESP.Update(), toolTip = "Chams" },
                new ButtonInfo { buttonText = "Skeleton ESP", enableMethod = () => VisualESP.SkeletonEsp = true, disableMethod = () => VisualESP.SkeletonEsp = false, method = () => VisualESP.Update(), toolTip = "Skeleton ESP" },
                new ButtonInfo { buttonText = "Name Tags", enableMethod = () => VisualESP.NameTags = true, disableMethod = () => VisualESP.NameTags = false, method = () => VisualESP.Update(), toolTip = "Name Tags" },
                new ButtonInfo { buttonText = "Index Tags", enableMethod = () => VisualESP.IndexTags = true, disableMethod = () => VisualESP.IndexTags = false, method = () => VisualESP.Update(), toolTip = "Index Tags" },
                new ButtonInfo { buttonText = "Box ESP", enableMethod = () => VisualESP.BoxEsp = true, disableMethod = () => VisualESP.BoxEsp = false, method = () => VisualESP.Update(), toolTip = "Box ESP" },
                new ButtonInfo { buttonText = "Box ESP 3D", enableMethod = () => VisualESP.BoxEsp3D = true, disableMethod = () => VisualESP.BoxEsp3D = false, method = () => VisualESP.Update(), toolTip = "Box ESP 3D" },
                new ButtonInfo { buttonText = "Corner ESP 3D", enableMethod = () => VisualESP.CornerEsp3D = true, disableMethod = () => VisualESP.CornerEsp3D = false, method = () => VisualESP.Update(), toolTip = "Corner ESP 3D" },
                new ButtonInfo { buttonText = "Box ESP 2D", enableMethod = () => VisualESP.BoxEsp2D = true, disableMethod = () => VisualESP.BoxEsp2D = false, method = () => VisualESP.Update(), toolTip = "Box ESP 2D" },
                new ButtonInfo { buttonText = "Corner ESP 2D", enableMethod = () => VisualESP.CornerEsp2D = true, disableMethod = () => VisualESP.CornerEsp2D = false, method = () => VisualESP.Update(), toolTip = "Corner ESP 2D" },
                new ButtonInfo { buttonText = "Bone ESP", enableMethod = () => VisualESP.BoneEsp = true, disableMethod = () => VisualESP.BoneEsp = false, method = () => VisualESP.Update(), toolTip = "Bone ESP" },
                new ButtonInfo { buttonText = "Tracers", enableMethod = () => VisualESP.Tracers = true, disableMethod = () => VisualESP.Tracers = false, method = () => VisualESP.Update(), toolTip = "Tracers" },
                new ButtonInfo { buttonText = "Trails", enableMethod = () => VisualESP.Trails = true, disableMethod = () => VisualESP.Trails = false, method = () => VisualESP.Update(), toolTip = "Trails" },
                new ButtonInfo { buttonText = "Distance ESP", enableMethod = () => VisualESP.DistanceEsp = true, disableMethod = () => VisualESP.DistanceEsp = false, method = () => VisualESP.Update(), toolTip = "Distance ESP" },
                new ButtonInfo { buttonText = "Galactic Orbit ESP", enableMethod = () => VisualESP.GalacticOrbit = true, disableMethod = () => VisualESP.GalacticOrbit = false, method = () => VisualESP.Update(), toolTip = "Galactic Orbit ESP" },
                new ButtonInfo { buttonText = "Grab Fling Tracers", enableMethod = () => GrabFling.TracersEnabled = true, disableMethod = () => GrabFling.TracersEnabled = false, method = () => GrabFling.Update(), toolTip = "Show who is gripping" },
                new ButtonInfo { buttonText = "Grab Fling All", enableMethod = () => GrabFling.AllEnabled = true, disableMethod = () => GrabFling.AllEnabled = false, method = () => GrabFling.Update(), toolTip = "Auto fling grippers" },

            },
            // 7 Global
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Speak Into Gun", enableMethod = () => VoiceGun.SpeakIntoGunEnabled = true, disableMethod = () => VoiceGun.SpeakIntoGunEnabled = false, method = () => VoiceGun.Update(), toolTip = "Your voice plays on aimed player's head." },
                new ButtonInfo { buttonText = "Speak From Newest", enableMethod = () => VoiceGun.ArmNewest(), disableMethod = () => VoiceGun.SpeakFromNewestEnabled = false, method = () => VoiceGun.Update(), toolTip = "Next joiner becomes voice puppet + mouth." },
                new ButtonInfo { buttonText = "VC Ban Newest", enableMethod = () => VoiceGun.VcBanNewest = true, disableMethod = () => VoiceGun.VcBanNewest = false, toolTip = "Flag/mute newest voice target." },
                new ButtonInfo { buttonText = "Debug Echo", enableMethod = () => VoiceGun.DebugEchoEnabled = true, disableMethod = () => VoiceGun.DebugEchoEnabled = false, method = () => VoiceGun.Update(), toolTip = "Hear yourself (loopback)." },
                new ButtonInfo { buttonText = "Voice Status", method = () => VoiceGun.Status(), isTogglable = false, toolTip = "Log voice gun state." },
                new ButtonInfo { buttonText = "CS Projectile", method = () => GlobalFun.ProjectileLaunchOnce(), isTogglable = false, toolTip = "CS Projectile" },
                new ButtonInfo { buttonText = "CS Projectile Launch", method = () => GlobalFun.ProjectileLaunchOnce(), isTogglable = false, toolTip = "CS Projectile Launch" },
                new ButtonInfo { buttonText = "CS Projectile Spam", enableMethod = () => GlobalFun.ProjectileSpam = true, disableMethod = () => GlobalFun.ProjectileSpam = false, method = () => GlobalFun.Update(), toolTip = "CS Projectile Spam" },
                new ButtonInfo { buttonText = "Clear Pool", method = () => GlobalFun.ClearPool(), isTogglable = false, toolTip = "Clear Pool" },
                new ButtonInfo { buttonText = "Snowball Effect All", method = () => GlobalFun.SnowballAll(), isTogglable = false, toolTip = "Snowball Effect All" },
                new ButtonInfo { buttonText = "Snowball Effect Gun", enableMethod = () => GlobalFun.SplashGun = true, disableMethod = () => GlobalFun.SplashGun = false, method = () => GlobalFun.Update(), toolTip = "Snowball Effect Gun" },
                new ButtonInfo { buttonText = "Stump Kick All", method = () => MenuStubs.StumpKickAll(), isTogglable = false, toolTip = "Stump Kick All" },
                new ButtonInfo { buttonText = "Stump Kick Gun", method = () => MenuStubs.StumpKickGun(), isTogglable = false, toolTip = "Stump Kick Gun" },
                new ButtonInfo { buttonText = "VIM Kick All", method = () => GlobalFun.VimKickAll(), isTogglable = false, toolTip = "VIM Kick All" },
                new ButtonInfo { buttonText = "VIM Kick Gun", enableMethod = () => GlobalFun.VimKickGun = true, disableMethod = () => GlobalFun.VimKickGun = false, method = () => GlobalFun.Update(), toolTip = "VIM Kick Gun" },
                new ButtonInfo { buttonText = "VIM Mute All", method = () => GlobalFun.VimMuteAll(), isTogglable = false, toolTip = "VIM Mute All" },
                new ButtonInfo { buttonText = "VIM Mute Gun", enableMethod = () => GlobalFun.VimMuteGun = true, disableMethod = () => GlobalFun.VimMuteGun = false, method = () => GlobalFun.Update(), toolTip = "VIM Mute Gun" },
                new ButtonInfo { buttonText = "VIM Timeout All", method = () => GlobalFun.VimTimeoutAll(), isTogglable = false, toolTip = "VIM Timeout All" },
                new ButtonInfo { buttonText = "VIM Timeout Gun", enableMethod = () => GlobalFun.VimTimeoutGun = true, disableMethod = () => GlobalFun.VimTimeoutGun = false, method = () => GlobalFun.Update(), toolTip = "VIM Timeout Gun" },
                new ButtonInfo { buttonText = "VIM Unmute All", method = () => GlobalFun.VimUnmuteAll(), isTogglable = false, toolTip = "VIM Unmute All" },
                new ButtonInfo { buttonText = "VIM Unmute Gun", method = () => MenuStubs.VimUnmuteGun(), isTogglable = false, toolTip = "VIM Unmute Gun" },
                new ButtonInfo { buttonText = "VIM Untimeout All", method = () => GlobalFun.VimUntimeoutAll(), isTogglable = false, toolTip = "VIM Untimeout All" },
                new ButtonInfo { buttonText = "VIM Untimeout Gun", method = () => MenuStubs.VimUntimeoutGun(), isTogglable = false, toolTip = "VIM Untimeout Gun" },
                new ButtonInfo { buttonText = "Hoverboard Anywhere", method = () => MenuStubs.HoverboardAnywhere(), isTogglable = false, toolTip = "Hoverboard Anywhere" },
                new ButtonInfo { buttonText = "RGB Hoverboard", method = () => MenuStubs.RGBHoverboard(), isTogglable = false, toolTip = "RGB Hoverboard" },
                new ButtonInfo { buttonText = "Hoverboard Blink", method = () => MenuStubs.HoverboardBlink(), isTogglable = false, toolTip = "Hoverboard Blink" },
                new ButtonInfo { buttonText = "Hoverboard Orbit", method = () => MenuStubs.HoverboardOrbit(), isTogglable = false, toolTip = "Hoverboard Orbit" },
                new ButtonInfo { buttonText = "Hoverboard Spaz", method = () => MenuStubs.HoverboardSpaz(), isTogglable = false, toolTip = "Hoverboard Spaz" },
                new ButtonInfo { buttonText = "Hoverboard Speed Boost", method = () => MenuStubs.HoverboardSpeedBoost(), isTogglable = false, toolTip = "Hoverboard Speed Boost" },
                new ButtonInfo { buttonText = "Hoverboard Moon Jump", method = () => MenuStubs.HoverboardMoonJump(), isTogglable = false, toolTip = "Hoverboard Moon Jump" },
                new ButtonInfo { buttonText = "Board Rain", enableMethod = () => GlobalFun.BoardRain = true, disableMethod = () => GlobalFun.BoardRain = false, method = () => GlobalFun.Update(), toolTip = "Board Rain" },
                new ButtonInfo { buttonText = "Board Shooter", method = () => MenuStubs.BoardShooter(), isTogglable = false, toolTip = "Board Shooter" },
                new ButtonInfo { buttonText = "Board Swarm", enableMethod = () => GlobalFun.BoardSwarm = true, disableMethod = () => GlobalFun.BoardSwarm = false, method = () => GlobalFun.Update(), toolTip = "Board Swarm" },
                new ButtonInfo { buttonText = "Board Trail", method = () => MenuStubs.BoardTrail(), isTogglable = false, toolTip = "Board Trail" },
                new ButtonInfo { buttonText = "Board Drop Gun", method = () => MenuStubs.BoardDropGun(), isTogglable = false, toolTip = "Board Drop Gun" },
                new ButtonInfo { buttonText = "Give Board Gun", method = () => MenuStubs.GiveBoardGun(), isTogglable = false, toolTip = "Give Board Gun" },
                new ButtonInfo { buttonText = "Splash Aura", enableMethod = () => GlobalFun.SplashAura = true, disableMethod = () => GlobalFun.SplashAura = false, method = () => GlobalFun.Update(), toolTip = "Splash Aura" },
                new ButtonInfo { buttonText = "Splash Hands", method = () => MenuStubs.SplashHands(), isTogglable = false, toolTip = "Splash Hands" },
                new ButtonInfo { buttonText = "Splash Trail", method = () => MenuStubs.SplashTrail(), isTogglable = false, toolTip = "Splash Trail" },
                new ButtonInfo { buttonText = "Splash Geyser", method = () => MenuStubs.SplashGeyser(), isTogglable = false, toolTip = "Splash Geyser" },
                new ButtonInfo { buttonText = "Splash Spiral", method = () => MenuStubs.SplashSpiral(), isTogglable = false, toolTip = "Splash Spiral" },
                new ButtonInfo { buttonText = "Splash Rain", method = () => MenuStubs.SplashRain(), isTogglable = false, toolTip = "Splash Rain" },
                new ButtonInfo { buttonText = "Splash Gun", enableMethod = () => GlobalFun.SplashGun = true, disableMethod = () => GlobalFun.SplashGun = false, method = () => GlobalFun.Update(), toolTip = "Splash Gun" },
                new ButtonInfo { buttonText = "Splash Player Gun", method = () => MenuStubs.SplashPlayerGun(), isTogglable = false, toolTip = "Splash Player Gun" },
                new ButtonInfo { buttonText = "Splash All Players", method = () => GlobalFun.SplashAllPlayers(), isTogglable = false, toolTip = "Splash All Players" },
                new ButtonInfo { buttonText = "Swim In Air", enableMethod = () => GlobalFun.SwimInAir = true, disableMethod = () => GlobalFun.SwimInAir = false, method = () => GlobalFun.Update(), toolTip = "Swim In Air" },
                new ButtonInfo { buttonText = "Water Walk", enableMethod = () => GlobalFun.WaterWalk = true, disableMethod = () => GlobalFun.WaterWalk = false, method = () => GlobalFun.Update(), toolTip = "Water Walk" },
                new ButtonInfo { buttonText = "Super Swim", enableMethod = () => GlobalFun.SuperSwim = true, disableMethod = () => GlobalFun.SuperSwim = false, method = () => GlobalFun.Update(), toolTip = "Super Swim" },
                new ButtonInfo { buttonText = "Voice Feedback", method = () => MenuStubs.VoiceFeedback(), isTogglable = false, toolTip = "Voice Feedback" },
                new ButtonInfo { buttonText = "Chipmunk Voice", method = () => MenuStubs.ChipmunkVoice(), isTogglable = false, toolTip = "Chipmunk Voice" },
                new ButtonInfo { buttonText = "Robot Voice", method = () => MenuStubs.RobotVoice(), isTogglable = false, toolTip = "Robot Voice" },
                new ButtonInfo { buttonText = "Radio Voice", method = () => MenuStubs.RadioVoice(), isTogglable = false, toolTip = "Radio Voice" },
                new ButtonInfo { buttonText = "Old Mic Voice", method = () => MenuStubs.OldMicVoice(), isTogglable = false, toolTip = "Old Mic Voice" },
                new ButtonInfo { buttonText = "Echo Voice", method = () => MenuStubs.EchoVoice(), isTogglable = false, toolTip = "Echo Voice" },
                new ButtonInfo { buttonText = "Stutter Voice", method = () => MenuStubs.StutterVoice(), isTogglable = false, toolTip = "Stutter Voice" },
                new ButtonInfo { buttonText = "Rope Gun", method = () => MenuStubs.RopeGunG(), isTogglable = false, toolTip = "Rope Gun" },
                new ButtonInfo { buttonText = "Rope Spaz", method = () => MenuStubs.RopeSpazG(), isTogglable = false, toolTip = "Rope Spaz" },
                new ButtonInfo { buttonText = "Rope Helicopter", method = () => MenuStubs.RopeHelicopter(), isTogglable = false, toolTip = "Rope Helicopter" },
                new ButtonInfo { buttonText = "Rope Tornado", method = () => MenuStubs.RopeTornado(), isTogglable = false, toolTip = "Rope Tornado" },
                new ButtonInfo { buttonText = "Rope Freeze", method = () => MenuStubs.RopeFreeze(), isTogglable = false, toolTip = "Rope Freeze" },
                new ButtonInfo { buttonText = "Block Grab Gun", method = () => MenuStubs.BlockGrabGun(), isTogglable = false, toolTip = "Block Grab Gun" },
                new ButtonInfo { buttonText = "Block Launcher Gun", method = () => MenuStubs.BlockLauncherGun(), isTogglable = false, toolTip = "Block Launcher Gun" },
                new ButtonInfo { buttonText = "Block Yeet", method = () => MenuStubs.BlockYeet(), isTogglable = false, toolTip = "Block Yeet" },
                new ButtonInfo { buttonText = "Steal Blocks Gun", method = () => MenuStubs.StealBlocksGun(), isTogglable = false, toolTip = "Steal Blocks Gun" },
                new ButtonInfo { buttonText = "Recycle Gun", method = () => MenuStubs.RecycleGun(), isTogglable = false, toolTip = "Recycle Gun" },
                new ButtonInfo { buttonText = "Recycle All Blocks", method = () => MenuStubs.RecycleAllBlocks(), isTogglable = false, toolTip = "Recycle All Blocks" },
                new ButtonInfo { buttonText = "Block Nuke", method = () => MenuStubs.BlockNuke(), isTogglable = false, toolTip = "Block Nuke" },
                new ButtonInfo { buttonText = "Block Tornado", method = () => MenuStubs.BlockTornado(), isTogglable = false, toolTip = "Block Tornado" },
                new ButtonInfo { buttonText = "Conveyor Spam", method = () => MenuStubs.ConveyorSpam(), isTogglable = false, toolTip = "Conveyor Spam" },
            },
            // 8 Overpowered
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Crash Gun", enableMethod = () => CrashGun.Enabled = true, disableMethod = () => CrashGun.Enabled = false, method = () => CrashGun.Update(), toolTip = "Crash gun" },
                new ButtonInfo { buttonText = "CrashGun Instant", enableMethod = () => CrashGunInstant.Enabled = true, disableMethod = () => CrashGunInstant.Enabled = false, method = () => CrashGunInstant.Update(), toolTip = "Instant crash" },
                new ButtonInfo { buttonText = "CrashGun Stealth", enableMethod = () => CrashGunStealth.Enabled = true, disableMethod = () => CrashGunStealth.Enabled = false, method = () => CrashGunStealth.Update(), toolTip = "Stealth / low-signature crash" },
                new ButtonInfo { buttonText = "CrashGun Classic", enableMethod = () => CrashGunClassic.Enabled = true, disableMethod = () => CrashGunClassic.Enabled = false, method = () => CrashGunClassic.Update(), toolTip = "Classic" },
                new ButtonInfo { buttonText = "CrashGun Silent", enableMethod = () => CrashGunSilent.Enabled = true, disableMethod = () => CrashGunSilent.Enabled = false, method = () => CrashGunSilent.Update(), toolTip = "Silent" },
                new ButtonInfo { buttonText = "CrashGun Ownership", enableMethod = () => CrashGunOwnership.Enabled = true, disableMethod = () => CrashGunOwnership.Enabled = false, method = () => CrashGunOwnership.Update(), toolTip = "Ownership" },
                new ButtonInfo { buttonText = "CrashGun Nuke", enableMethod = () => CrashGunNuke.Enabled = true, disableMethod = () => CrashGunNuke.Enabled = false, method = () => CrashGunNuke.Update(), toolTip = "Nuke" },
                new ButtonInfo { buttonText = "CrashGun AntiBan", enableMethod = () => CrashGunAntiBan.Enabled = true, disableMethod = () => CrashGunAntiBan.Enabled = false, method = () => CrashGunAntiBan.Update(), toolTip = "AntiBan room gun" },
                new ButtonInfo { buttonText = "Kick Gun", enableMethod = () => KickGun.Enabled = true, disableMethod = () => KickGun.Enabled = false, method = () => KickGun.Update(), toolTip = "Force-leave kick gun" },
                new ButtonInfo { buttonText = "Barrel Fling Gun", enableMethod = () => BarrelFlingGun.Enabled = true, disableMethod = () => BarrelFlingGun.Enabled = false, method = () => BarrelFlingGun.Update(), toolTip = "Spin body fast - fling target" },
                new ButtonInfo { buttonText = "Lag Gun", enableMethod = () => LagGun.Enabled = true, disableMethod = () => LagGun.Enabled = false, method = () => LagGun.Update(), toolTip = "Lag spike gun" },
                new ButtonInfo { buttonText = "Freeze Gun", enableMethod = () => FreezeGun.Enabled = true, disableMethod = () => FreezeGun.Enabled = false, method = () => FreezeGun.Update(), toolTip = "Ownership freeze gun" },
                new ButtonInfo { buttonText = "Rope Up", enableMethod = () => RopeControl.RopeUpEnabled = true, disableMethod = () => RopeControl.RopeUpEnabled = false, method = () => RopeControl.Update(), toolTip = "Ropes up" },
                new ButtonInfo { buttonText = "Rope Down", enableMethod = () => RopeControl.RopeDownEnabled = true, disableMethod = () => RopeControl.RopeDownEnabled = false, method = () => RopeControl.Update(), toolTip = "Ropes down" },
                new ButtonInfo { buttonText = "Rope Spaz", enableMethod = () => RopeControl.RopeSpazEnabled = true, disableMethod = () => RopeControl.RopeSpazEnabled = false, method = () => RopeControl.Update(), toolTip = "Rope spaz" },
                new ButtonInfo { buttonText = "Rope Pull Gun", enableMethod = () => RopeControl.RopeGunEnabled = true, disableMethod = () => RopeControl.RopeGunEnabled = false, method = () => RopeControl.Update(), toolTip = "Pull ropes to target" },
                new ButtonInfo { buttonText = "Mat Spam", enableMethod = () => NetworkOddities.MatSpamEnabled = true, disableMethod = () => NetworkOddities.MatSpamEnabled = false, method = () => NetworkOddities.Update(), toolTip = "Material event spam" },
                new ButtonInfo { buttonText = "Log Spam", enableMethod = () => NetworkOddities.LogSpamEnabled = true, disableMethod = () => NetworkOddities.LogSpamEnabled = false, method = () => NetworkOddities.Update(), toolTip = "Log/string spam" },
                new ButtonInfo { buttonText = "Instantiate Spam", enableMethod = () => NetworkOddities.InstantiateSpamEnabled = true, disableMethod = () => NetworkOddities.InstantiateSpamEnabled = false, method = () => NetworkOddities.Update(), toolTip = "Event 200 spam" },
                new ButtonInfo { buttonText = "Destroy Spam", enableMethod = () => NetworkOddities.DestroySpamEnabled = true, disableMethod = () => NetworkOddities.DestroySpamEnabled = false, method = () => NetworkOddities.Update(), toolTip = "Event 201 spam" },
                new ButtonInfo { buttonText = "Ban Gun", enableMethod = () => BanGun.Enabled = true, disableMethod = () => BanGun.Enabled = false, method = () => BanGun.Update(), toolTip = "Ban gun" },
                new ButtonInfo { buttonText = "Ban All", method = () => BanGun.BanAll(), isTogglable = false, toolTip = "Ban all" },
                new ButtonInfo { buttonText = "Server Crasher", enableMethod = () => { ServerCrasher.Enabled = true; ServerCrasher.HardStress(); }, disableMethod = () => ServerCrasher.Enabled = false, method = () => ServerCrasher.Update(), toolTip = "Server crash" },
                new ButtonInfo { buttonText = "Server Overload", enableMethod = () => { ServerOverload.Enabled = true; ServerOverload.Hard(); }, disableMethod = () => ServerOverload.Enabled = false, method = () => ServerOverload.Update(), toolTip = "Overload" },
                new ButtonInfo { buttonText = "Join Ping Crasher", enableMethod = () => { JoinPingCrasher.Enabled = true; JoinPingCrasher.Hard(); }, disableMethod = () => JoinPingCrasher.Enabled = false, method = () => JoinPingCrasher.Update(), toolTip = "Join pings" },
                new ButtonInfo { buttonText = "Overload Now", method = () => ServerOverload.OverloadNow(), isTogglable = false, toolTip = "Burst" },
                new ButtonInfo { buttonText = "Stump Anti-Ban", method = () => MenuStubs.StumpAntiBan(), isTogglable = false, toolTip = "Stump Anti-Ban" },
                new ButtonInfo { buttonText = "Party Anti-Ban", method = () => MenuStubs.PartyAntiBan(), isTogglable = false, toolTip = "Party Anti-Ban" },
                new ButtonInfo { buttonText = "Kick Casual", method = () => ModeKicks.KickCasual(), isTogglable = false, toolTip = "Kick Casual" },
                new ButtonInfo { buttonText = "Kick Infection", method = () => ModeKicks.KickInfection(), isTogglable = false, toolTip = "Kick Infection" },
                new ButtonInfo { buttonText = "Kick Hunt Down", method = () => ModeKicks.KickHuntDown(), isTogglable = false, toolTip = "Kick Hunt Down" },
                new ButtonInfo { buttonText = "Kick Paintbrawl", method = () => ModeKicks.KickPaintbrawl(), isTogglable = false, toolTip = "Kick Paintbrawl" },
                new ButtonInfo { buttonText = "Kick Guardian", method = () => ModeKicks.KickGuardian(), isTogglable = false, toolTip = "Kick Guardian" },
                new ButtonInfo { buttonText = "Kick Ambush", method = () => ModeKicks.KickAmbush(), isTogglable = false, toolTip = "Kick Ambush" },
                new ButtonInfo { buttonText = "Kick Ghost", method = () => ModeKicks.KickGhost(), isTogglable = false, toolTip = "Kick Ghost" },
                new ButtonInfo { buttonText = "Kick Freeze Tag", method = () => ModeKicks.KickFreezeTag(), isTogglable = false, toolTip = "Kick Freeze Tag" },
                new ButtonInfo { buttonText = "Kick Custom", method = () => ModeKicks.KickCustom(), isTogglable = false, toolTip = "Kick Custom" },
                new ButtonInfo { buttonText = "Kick Prop Hunt", method = () => ModeKicks.KickPropHunt(), isTogglable = false, toolTip = "Kick Prop Hunt" },
                new ButtonInfo { buttonText = "Kick Super Infect", method = () => ModeKicks.KickSuperInfect(), isTogglable = false, toolTip = "Kick Super Infect" },
                new ButtonInfo { buttonText = "Kick Infection Comp", method = () => ModeKicks.KickInfectionComp(), isTogglable = false, toolTip = "Kick Infection Comp" },
                new ButtonInfo { buttonText = "Lag Spike All", method = () => MenuStubs.LagSpikeAll(), isTogglable = false, toolTip = "Lag Spike All" },
                new ButtonInfo { buttonText = "Lag Spike Gun", enableMethod = () => LagGun.Enabled = true, disableMethod = () => LagGun.Enabled = false, method = () => LagGun.Update(), toolTip = "Lag Spike Gun" },
                new ButtonInfo { buttonText = "Hard Lag All", method = () => MenuStubs.HardLagAll(), isTogglable = false, toolTip = "Hard Lag All" },
                new ButtonInfo { buttonText = "Hard Lag Gun", enableMethod = () => LagGun.Enabled = true, disableMethod = () => LagGun.Enabled = false, method = () => LagGun.Update(), toolTip = "Hard Lag Gun" },
                new ButtonInfo { buttonText = "Weak Lag All", method = () => MenuStubs.WeakLagAll(), isTogglable = false, toolTip = "Weak Lag All" },
                new ButtonInfo { buttonText = "Weak Lag Gun", enableMethod = () => LagGun.Enabled = true, disableMethod = () => LagGun.Enabled = false, method = () => LagGun.Update(), toolTip = "Weak Lag Gun" },
                new ButtonInfo { buttonText = "Spy Room", method = () => MenuStubs.SpyRoom(), isTogglable = false, toolTip = "Spy Room" },
                new ButtonInfo { buttonText = "Kick New Joiners", method = () => ModeKicks.KickNewJoiners(), isTogglable = false, toolTip = "Kick New Joiners" },
                new ButtonInfo { buttonText = "Destroy All", method = () => MenuStubs.DestroyAll(), isTogglable = false, toolTip = "Destroy All" },
                new ButtonInfo { buttonText = "Destroy Others", method = () => MenuStubs.DestroyOthers(), isTogglable = false, toolTip = "Destroy Others" },
                new ButtonInfo { buttonText = "Destroy Gun", method = () => MenuStubs.DestroyGun(), isTogglable = false, toolTip = "Destroy Gun" },
                new ButtonInfo { buttonText = "Destroy Aura", method = () => MenuStubs.DestroyAura(), isTogglable = false, toolTip = "Destroy Aura" },
                new ButtonInfo { buttonText = "Deafen All", method = () => MenuStubs.DeafenAll(), isTogglable = false, toolTip = "Deafen All" },
                new ButtonInfo { buttonText = "Deafen Others", method = () => MenuStubs.DeafenOthers(), isTogglable = false, toolTip = "Deafen Others" },
                new ButtonInfo { buttonText = "Deafen Gun", method = () => MenuStubs.DeafenGun(), isTogglable = false, toolTip = "Deafen Gun" },
                new ButtonInfo { buttonText = "Deafen Aura", method = () => MenuStubs.DeafenAura(), isTogglable = false, toolTip = "Deafen Aura" },
            },
            // 9 Experimental
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Voice Stabilizer", enableMethod = () => VoiceStabilizer.Enabled = true, disableMethod = () => VoiceStabilizer.Enabled = false, method = () => VoiceStabilizer.Update(), toolTip = "Constant voice level" },
                new ButtonInfo { buttonText = "Force Add Friend", enableMethod = () => FriendTools.ForceAddFriendEnabled = true, disableMethod = () => FriendTools.ForceAddFriendEnabled = false, method = () => FriendTools.Update(), toolTip = "Auto friend in range" },
                new ButtonInfo { buttonText = "Friend Code Spoof", enableMethod = () => FriendTools.FriendCodeSpoofEnabled = true, disableMethod = () => FriendTools.FriendCodeSpoofEnabled = false, method = () => FriendTools.Update(), toolTip = "Spoof display code kkk" },
                new ButtonInfo { buttonText = "Break Add Friend", enableMethod = () => FriendTools.BreakAddFriendEnabled = true, disableMethod = () => FriendTools.BreakAddFriendEnabled = false, method = () => FriendTools.Update(), toolTip = "Break friend machine" },
                new ButtonInfo { buttonText = "Spam Bracelet", enableMethod = () => FriendTools.SpamBraceletEnabled = true, disableMethod = () => FriendTools.SpamBraceletEnabled = false, method = () => FriendTools.Update(), toolTip = "Bracelet spam" },
                new ButtonInfo { buttonText = "Instant Friendship", enableMethod = () => FriendTools.InstantFriendshipEnabled = true, disableMethod = () => FriendTools.InstantFriendshipEnabled = false, method = () => FriendTools.Update(), toolTip = "Instant bracelet all" },
                new ButtonInfo { buttonText = "Tentacle Gun", enableMethod = () => TentacleGun.Enabled = true, disableMethod = () => TentacleGun.Enabled = false, method = () => TentacleGun.Update(), toolTip = "Squiggly tentacle line" },
                new ButtonInfo { buttonText = "PC Click Buttons", enableMethod = () => PcClick.Enabled = true, disableMethod = () => PcClick.Enabled = false, method = () => PcClick.Update(), toolTip = "Mouse click in-game buttons" },
                new ButtonInfo { buttonText = "Spoof Everything", enableMethod = () => SpoofEverything.Enabled = true, disableMethod = () => SpoofEverything.Enabled = false, method = () => SpoofEverything.Update(), toolTip = "Name color cosmetics" },
                new ButtonInfo { buttonText = "Mute Bypass", enableMethod = () => AntiMute.Enable(), disableMethod = () => AntiMute.Disable(), method = () => AntiMute.Update(), enabled = true, toolTip = "Mute bypass - keep voice up through mute flags/props." },
                new ButtonInfo { buttonText = "Force Unmute Now", method = () => AntiMute.ForceUnmute(), isTogglable = false, toolTip = "Local + replicated room/actor unmute now." },
                new ButtonInfo { buttonText = "Take Master For Unmute", enableMethod = () => AntiMute.TakeMasterIfNeeded = true, disableMethod = () => AntiMute.TakeMasterIfNeeded = false, enabled = true, toolTip = "Claim master so room mute table can be written." },
                new ButtonInfo { buttonText = "Broadcast Unmute", enableMethod = () => AntiMute.BroadcastUnmuteEvent = true, disableMethod = () => AntiMute.BroadcastUnmuteEvent = false, enabled = true, toolTip = "RaiseEvent unmute hint to peers." },
                new ButtonInfo { buttonText = "AntiMute Status", method = () => AntiMute.Status(), isTogglable = false, toolTip = "Log AntiMute state." },
            },
            // 10 Anti-Ban Mods
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Anti-Ban", enableMethod = () => AntiBan.Enable(), disableMethod = () => AntiBan.Disable(), method = () => AntiBan.Update(), enabled = true, toolTip = "Core anti-ban" },

                new ButtonInfo { buttonText = "Anti Report", enableMethod = () => AntiReport.Enabled = true, disableMethod = () => AntiReport.Enabled = false, method = () => AntiReport.Update(), toolTip = "Disconnect on report detect" },
                new ButtonInfo { buttonText = "Stump Kick Fix Gun", enableMethod = () => StumpKickFix.GunEnabled = true, disableMethod = () => StumpKickFix.GunEnabled = false, method = () => StumpKickFix.Update(), toolTip = "Hardened kick-to-code gun" },
                new ButtonInfo { buttonText = "Stump Kick Fix All", method = () => StumpKickFix.KickAllToCode(), isTogglable = false, toolTip = "Kick all to code" },
                new ButtonInfo { buttonText = "AB Kick Gun", enableMethod = () => AntiBanGhostOps.KickGunEnabled = true, disableMethod = () => AntiBanGhostOps.KickGunEnabled = false, method = () => AntiBanGhostOps.Update(), toolTip = "Antiban room kick gun" },
                new ButtonInfo { buttonText = "AB Crash Gun", enableMethod = () => AntiBanGhostOps.CrashGunEnabled = true, disableMethod = () => AntiBanGhostOps.CrashGunEnabled = false, method = () => AntiBanGhostOps.Update(), toolTip = "Antiban room crash gun" },
                new ButtonInfo { buttonText = "AB Full Invis Gun", enableMethod = () => AntiBanGhostOps.FullInvisGunEnabled = true, disableMethod = () => AntiBanGhostOps.FullInvisGunEnabled = false, method = () => AntiBanGhostOps.Update(), toolTip = "Hide target + blank peers" },

                new ButtonInfo { buttonText = "Name Spoof", enableMethod = () => IdentitySafety.NameSpoofEnabled = true, disableMethod = () => IdentitySafety.NameSpoofEnabled = false, method = () => IdentitySafety.Update(), toolTip = "Spoof nickname" },
                new ButtonInfo { buttonText = "Color Spoof", enableMethod = () => IdentitySafety.ColorSpoofEnabled = true, disableMethod = () => IdentitySafety.ColorSpoofEnabled = false, method = () => IdentitySafety.Update(), toolTip = "Cycle color props" },
                new ButtonInfo { buttonText = "Anti AFK", enableMethod = () => IdentitySafety.AntiAfkEnabled = true, disableMethod = () => IdentitySafety.AntiAfkEnabled = false, method = () => IdentitySafety.Update(), toolTip = "Anti AFK pulse" },
                new ButtonInfo { buttonText = "Flush RPCs", enableMethod = () => IdentitySafety.FlushRpcEnabled = true, disableMethod = () => IdentitySafety.FlushRpcEnabled = false, method = () => IdentitySafety.Update(), toolTip = "Flush RPC backlog" },
                new ButtonInfo { buttonText = "Create Private NoAC", method = () => AntiBanRoom.CreatePrivateNoAC(), isTogglable = false, toolTip = "Private code room no AC" },
                new ButtonInfo { buttonText = "Create AntiBan Room", method = () => AntiBanRoom.Create(), isTogglable = false, toolTip = "Private code room" },
                new ButtonInfo { buttonText = "AntiBan Room Hold", enableMethod = () => AntiBanRoom.Enabled = true, disableMethod = () => AntiBanRoom.Enabled = false, method = () => AntiBanRoom.Update(), toolTip = "Hold room" },
                new ButtonInfo { buttonText = "Convert Room AntiBan", method = () => AntiBanRoom.ConvertCurrent(), isTogglable = false, toolTip = "Convert" },
                new ButtonInfo { buttonText = "Lock And Clear", method = () => AntiBanRoom.LockAndClear(), isTogglable = false, toolTip = "Lock+kick" },
                new ButtonInfo { buttonText = "Kick Joiners", enableMethod = () => AntiBanRoom.KickJoiners = true, disableMethod = () => AntiBanRoom.KickJoiners = false, toolTip = "Kick joiners" },
                new ButtonInfo { buttonText = "Ghost All", method = () => GhostVariants.GhostAll(), isTogglable = false, toolTip = "Ghost All" },
                new ButtonInfo { buttonText = "Ghost Gun", enableMethod = () => GhostVariants.GhostGunEnabled = true, disableMethod = () => GhostVariants.GhostGunEnabled = false, method = () => GhostVariants.Update(), toolTip = "Ghost Gun" },
                new ButtonInfo { buttonText = "Ghost Aura", enableMethod = () => GhostVariants.GhostAuraEnabled = true, disableMethod = () => GhostVariants.GhostAuraEnabled = false, method = () => GhostVariants.Update(), toolTip = "Ghost Aura" },
                new ButtonInfo { buttonText = "Ghost When Touched", enableMethod = () => GhostVariants.GhostWhenTouched = true, disableMethod = () => GhostVariants.GhostWhenTouched = false, method = () => GhostVariants.Update(), toolTip = "Ghost When Touched" },
                new ButtonInfo { buttonText = "Ghost On Your Touch", enableMethod = () => GhostVariants.GhostOnYourTouch = true, disableMethod = () => GhostVariants.GhostOnYourTouch = false, method = () => GhostVariants.Update(), toolTip = "Ghost On Your Touch" },
                new ButtonInfo { buttonText = "Revoke Ghost All", method = () => GhostVariants.RevokeGhostAll(), isTogglable = false, toolTip = "Revoke Ghost All" },
                new ButtonInfo { buttonText = "Revoke Ghost Gun", method = () => GhostVariants.RevokeGhostGun(), isTogglable = false, toolTip = "Revoke Ghost Gun" },
                new ButtonInfo { buttonText = "Revoke Ghost On Your Touch", method = () => MenuStubs.RevokeGhostOnYourTouch(), isTogglable = false, toolTip = "Revoke Ghost On Your Touch" },
                new ButtonInfo { buttonText = "Hard Lag All", method = () => MenuStubs.HardLagAll(), isTogglable = false, toolTip = "Hard Lag All" },
                new ButtonInfo { buttonText = "Hard Lag Gun", method = () => MenuStubs.HardLagGun(), isTogglable = false, toolTip = "Hard Lag Gun" },
                new ButtonInfo { buttonText = "Hard Lag Aura", method = () => MenuStubs.HardLagAura(), isTogglable = false, toolTip = "Hard Lag Aura" },
                new ButtonInfo { buttonText = "Hard Lag When Touched", method = () => MenuStubs.HardLagWhenTouched(), isTogglable = false, toolTip = "Hard Lag When Touched" },
                new ButtonInfo { buttonText = "Change Name All", method = () => MenuStubs.ChangeNameAll(), isTogglable = false, toolTip = "Change Name All" },
                new ButtonInfo { buttonText = "Change Name Gun", method = () => MenuStubs.ChangeNameGun(), isTogglable = false, toolTip = "Change Name Gun" },
                new ButtonInfo { buttonText = "Break Game Mode", method = () => MenuStubs.BreakGameMode(), isTogglable = false, toolTip = "Break Game Mode" },
            },
            // 11 Master
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 0, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "</> Super Infection </>", method = () => currentCategory = 12, isTogglable = false, toolTip = "Super Infection" },
                new ButtonInfo { buttonText = "Flicker Object Gun", enableMethod = () => MasterSI.FlickerObjectGun = true, disableMethod = () => MasterSI.FlickerObjectGun = false, method = () => MasterSI.Update(), toolTip = "Flicker Object Gun" },
                new ButtonInfo { buttonText = "Give Master Gun", enableMethod = () => MasterSI.GiveMasterGun = true, disableMethod = () => MasterSI.GiveMasterGun = false, method = () => MasterSI.Update(), toolTip = "Give Master Gun" },
                new ButtonInfo { buttonText = "Untag Gun", enableMethod = () => MasterSI.UntagGun = true, disableMethod = () => MasterSI.UntagGun = false, method = () => MasterSI.Update(), toolTip = "Untag Gun" },
                new ButtonInfo { buttonText = "Untag All", method = () => MasterSI.UntagAll(), isTogglable = false, toolTip = "Untag All" },
                new ButtonInfo { buttonText = "Untag Self", method = () => MasterSI.UntagSelf(), isTogglable = false, toolTip = "Untag Self" },
                new ButtonInfo { buttonText = "Untag Aura", enableMethod = () => MasterSI.UntagAura = true, disableMethod = () => MasterSI.UntagAura = false, method = () => MasterSI.Update(), toolTip = "Untag Aura" },
                new ButtonInfo { buttonText = "Material Gun", enableMethod = () => MasterSI.MaterialGun = true, disableMethod = () => MasterSI.MaterialGun = false, method = () => MasterSI.Update(), toolTip = "Material Gun" },
                new ButtonInfo { buttonText = "Material All", method = () => MasterSI.MaterialAll(), isTogglable = false, toolTip = "Material All" },
                new ButtonInfo { buttonText = "Material Self", method = () => MasterSI.MaterialSelf(), isTogglable = false, toolTip = "Material Self" },
                new ButtonInfo { buttonText = "Material Aura", enableMethod = () => MasterSI.MaterialAura = true, disableMethod = () => MasterSI.MaterialAura = false, method = () => MasterSI.Update(), toolTip = "Material Aura" },
                new ButtonInfo { buttonText = "Cause Tag Lag", method = () => MasterSI.CauseTagLag(), isTogglable = false, toolTip = "Cause Tag Lag" },
                new ButtonInfo { buttonText = "Vibrate Gun", enableMethod = () => MasterSI.VibrateGun = true, disableMethod = () => MasterSI.VibrateGun = false, method = () => MasterSI.Update(), toolTip = "Vibrate Gun" },
                new ButtonInfo { buttonText = "Vibrate All", method = () => MasterSI.VibrateAll(), isTogglable = false, toolTip = "Vibrate All" },
                new ButtonInfo { buttonText = "Vibrate Aura", enableMethod = () => MasterSI.VibrateAura = true, disableMethod = () => MasterSI.VibrateAura = false, method = () => MasterSI.Update(), toolTip = "Vibrate Aura" },
                new ButtonInfo { buttonText = "Slow Gun", enableMethod = () => MasterSI.SlowGun = true, disableMethod = () => MasterSI.SlowGun = false, method = () => MasterSI.Update(), toolTip = "Slow Gun" },
                new ButtonInfo { buttonText = "Slow All", method = () => MasterSI.SlowAll(), isTogglable = false, toolTip = "Slow All" },
                new ButtonInfo { buttonText = "Slow Aura", enableMethod = () => MasterSI.SlowAura = true, disableMethod = () => MasterSI.SlowAura = false, method = () => MasterSI.Update(), toolTip = "Slow Aura" },
                new ButtonInfo { buttonText = "HitTarget Spam", enableMethod = () => MasterSI.HitTargetSpam = true, disableMethod = () => MasterSI.HitTargetSpam = false, method = () => MasterSI.Update(), toolTip = "HitTarget Spam" },
            },
            // 12 Super Infection
            new ButtonInfo[]
            {
                new ButtonInfo { buttonText = "</> Return </>", method = () => currentCategory = 11, isTogglable = false, toolTip = "Back." },
                new ButtonInfo { buttonText = "Material Orbit", enableMethod = () => MaterialOrbit.OrbitEnabled = true, disableMethod = () => MaterialOrbit.OrbitEnabled = false, method = () => MaterialOrbit.Update(), toolTip = "Material orbit" },
                new ButtonInfo { buttonText = "Material Gun", enableMethod = () => MaterialOrbit.GunEnabled = true, disableMethod = () => MaterialOrbit.GunEnabled = false, method = () => MaterialOrbit.Update(), toolTip = "Material gun" },
                new ButtonInfo { buttonText = "Material Spam", enableMethod = () => MaterialOrbit.SpamEnabled = true, disableMethod = () => MaterialOrbit.SpamEnabled = false, method = () => MaterialOrbit.Update(), toolTip = "Material spam" },
                new ButtonInfo { buttonText = "Material Star", enableMethod = () => MaterialOrbit.StarEnabled = true, disableMethod = () => MaterialOrbit.StarEnabled = false, method = () => MaterialOrbit.Update(), toolTip = "Material star" },
                new ButtonInfo { buttonText = "Gear Draw", enableMethod = () => GearDraw.Enabled = true, disableMethod = () => GearDraw.Enabled = false, method = () => GearDraw.Update(), toolTip = "Draw gear in air" },
                new ButtonInfo { buttonText = "Destroy Entity Gun", enableMethod = () => MasterSI.DestroyEntityGun = true, disableMethod = () => MasterSI.DestroyEntityGun = false, method = () => MasterSI.Update(), toolTip = "Destroy Entity Gun" },
                new ButtonInfo { buttonText = "Random Gadget Gun", enableMethod = () => MasterSI.RandomGadgetGun = true, disableMethod = () => MasterSI.RandomGadgetGun = false, method = () => MasterSI.Update(), toolTip = "Random Gadget Gun" },
                new ButtonInfo { buttonText = "Random Gadget Spam", method = () => MasterSI.RandomGadgetSpam(), isTogglable = false, toolTip = "Random Gadget Spam" },
                new ButtonInfo { buttonText = "Random Resource Gun", enableMethod = () => MasterSI.RandomResourceGun = true, disableMethod = () => MasterSI.RandomResourceGun = false, method = () => MasterSI.Update(), toolTip = "Random Resource Gun" },
                new ButtonInfo { buttonText = "Random Resource Spam", method = () => MasterSI.RandomResourceSpam(), isTogglable = false, toolTip = "Random Resource Spam" },
                new ButtonInfo { buttonText = "Blast Lobber Gun", enableMethod = () => MasterSI.BlastLobberGun = true, disableMethod = () => MasterSI.BlastLobberGun = false, method = () => MasterSI.Update(), toolTip = "Blast Lobber Gun" },
                new ButtonInfo { buttonText = "Blast Lobber Spam", method = () => MasterSI.BlastLobberSpam(), isTogglable = false, toolTip = "Blast Lobber Spam" },
                new ButtonInfo { buttonText = "Mega Charge Blaster Gun", enableMethod = () => MasterSI.MegaChargeGun = true, disableMethod = () => MasterSI.MegaChargeGun = false, method = () => MasterSI.Update(), toolTip = "Mega Charge Blaster Gun" },
                new ButtonInfo { buttonText = "Mega Charge Blaster Spam", method = () => MasterSI.MegaChargeSpam(), isTogglable = false, toolTip = "Mega Charge Blaster Spam" },
                new ButtonInfo { buttonText = "Weak Blaster Gun", enableMethod = () => MasterSI.WeakBlasterGun = true, disableMethod = () => MasterSI.WeakBlasterGun = false, method = () => MasterSI.Update(), toolTip = "Weak Blaster Gun" },
                new ButtonInfo { buttonText = "Weak Blaster Spam", method = () => MasterSI.WeakBlasterSpam(), isTogglable = false, toolTip = "Weak Blaster Spam" },
                new ButtonInfo { buttonText = "Long Blaster Gun", enableMethod = () => MasterSI.LongBlasterGun = true, disableMethod = () => MasterSI.LongBlasterGun = false, method = () => MasterSI.Update(), toolTip = "Long Blaster Gun" },
                new ButtonInfo { buttonText = "Long Blaster Spam", method = () => MasterSI.LongBlasterSpam(), isTogglable = false, toolTip = "Long Blaster Spam" },
                new ButtonInfo { buttonText = "Tentacle Arm Gun", enableMethod = () => MasterSI.TentacleArmGun = true, disableMethod = () => MasterSI.TentacleArmGun = false, method = () => MasterSI.Update(), toolTip = "Tentacle Arm Gun" },
                new ButtonInfo { buttonText = "Tentacle Arm Spam", method = () => MasterSI.TentacleArmSpam(), isTogglable = false, toolTip = "Tentacle Arm Spam" },
                new ButtonInfo { buttonText = "Air Juke Gun", enableMethod = () => MasterSI.AirJukeGun = true, disableMethod = () => MasterSI.AirJukeGun = false, method = () => MasterSI.Update(), toolTip = "Air Juke Gun" },
                new ButtonInfo { buttonText = "Air Juke Spam", method = () => MasterSI.AirJukeSpam(), isTogglable = false, toolTip = "Air Juke Spam" },
                new ButtonInfo { buttonText = "Laser Zipline Gun", enableMethod = () => MasterSI.LaserZiplineGun = true, disableMethod = () => MasterSI.LaserZiplineGun = false, method = () => MasterSI.Update(), toolTip = "Laser Zipline Gun" },
                new ButtonInfo { buttonText = "Laser Zipline Spam", method = () => MasterSI.LaserZiplineSpam(), isTogglable = false, toolTip = "Laser Zipline Spam" },
                new ButtonInfo { buttonText = "Dash Yoyo Gun", enableMethod = () => MasterSI.DashYoyoGun = true, disableMethod = () => MasterSI.DashYoyoGun = false, method = () => MasterSI.Update(), toolTip = "Dash Yoyo Gun" },
                new ButtonInfo { buttonText = "Dash Yoyo Spam", method = () => MasterSI.DashYoyoSpam(), isTogglable = false, toolTip = "Dash Yoyo Spam" },
                new ButtonInfo { buttonText = "Stilt Extendo Gun", enableMethod = () => MasterSI.StiltExtendoGun = true, disableMethod = () => MasterSI.StiltExtendoGun = false, method = () => MasterSI.Update(), toolTip = "Stilt Extendo Gun" },
                new ButtonInfo { buttonText = "Stilt Extendo Spam", method = () => MasterSI.StiltExtendoSpam(), isTogglable = false, toolTip = "Stilt Extendo Spam" },
                new ButtonInfo { buttonText = "Stilt Fixed Gun", enableMethod = () => MasterSI.StiltFixedGun = true, disableMethod = () => MasterSI.StiltFixedGun = false, method = () => MasterSI.Update(), toolTip = "Stilt Fixed Gun" },
                new ButtonInfo { buttonText = "Stilt Fixed Spam", method = () => MasterSI.StiltFixedSpam(), isTogglable = false, toolTip = "Stilt Fixed Spam" },
                new ButtonInfo { buttonText = "Platform Deployer Gun", enableMethod = () => MasterSI.PlatformDeployerGun = true, disableMethod = () => MasterSI.PlatformDeployerGun = false, method = () => MasterSI.Update(), toolTip = "Platform Deployer Gun" },
                new ButtonInfo { buttonText = "Platform Deployer Spam", method = () => MasterSI.PlatformDeployerSpam(), isTogglable = false, toolTip = "Platform Deployer Spam" },
                new ButtonInfo { buttonText = "Bouncy Platform Gun", enableMethod = () => MasterSI.BouncyPlatformGun = true, disableMethod = () => MasterSI.BouncyPlatformGun = false, method = () => MasterSI.Update(), toolTip = "Bouncy Platform Gun" },
                new ButtonInfo { buttonText = "Bouncy Platform Spam", method = () => MasterSI.BouncyPlatformSpam(), isTogglable = false, toolTip = "Bouncy Platform Spam" },
                new ButtonInfo { buttonText = "Weird Gear Gun", enableMethod = () => MasterSI.WeirdGearGun = true, disableMethod = () => MasterSI.WeirdGearGun = false, method = () => MasterSI.Update(), toolTip = "Weird Gear Gun" },
                new ButtonInfo { buttonText = "Weird Gear Spam", method = () => MasterSI.WeirdGearSpam(), isTogglable = false, toolTip = "Weird Gear Spam" },
                new ButtonInfo { buttonText = "Strange Wood Gun", enableMethod = () => MasterSI.StrangeWoodGun = true, disableMethod = () => MasterSI.StrangeWoodGun = false, method = () => MasterSI.Update(), toolTip = "Strange Wood Gun" },
                new ButtonInfo { buttonText = "Strange Wood Spam", method = () => MasterSI.StrangeWoodSpam(), isTogglable = false, toolTip = "Strange Wood Spam" },
                new ButtonInfo { buttonText = "Bouncy Sand Gun", enableMethod = () => MasterSI.BouncySandGun = true, disableMethod = () => MasterSI.BouncySandGun = false, method = () => MasterSI.Update(), toolTip = "Bouncy Sand Gun" },
                new ButtonInfo { buttonText = "Bouncy Sand Spam", method = () => MasterSI.BouncySandSpam(), isTogglable = false, toolTip = "Bouncy Sand Spam" },
                new ButtonInfo { buttonText = "Floppy Metal Gun", enableMethod = () => MasterSI.FloppyMetalGun = true, disableMethod = () => MasterSI.FloppyMetalGun = false, method = () => MasterSI.Update(), toolTip = "Floppy Metal Gun" },
                new ButtonInfo { buttonText = "Floppy Metal Spam", method = () => MasterSI.FloppyMetalSpam(), isTogglable = false, toolTip = "Floppy Metal Spam" },
                new ButtonInfo { buttonText = "Vibrating Spring Gun", enableMethod = () => MasterSI.VibratingSpringGun = true, disableMethod = () => MasterSI.VibratingSpringGun = false, method = () => MasterSI.Update(), toolTip = "Vibrating Spring Gun" },
                new ButtonInfo { buttonText = "Vibrating Spring Spam", method = () => MasterSI.VibratingSpringSpam(), isTogglable = false, toolTip = "Vibrating Spring Spam" },
            },
        };
    }
}
